import React, { useState, useEffect } from 'react';
import { Compass, CheckCircle2, ArrowRight, PackageCheck, AlertOctagon, Box, FileCheck, Zap, FileText, Layers, Plus, Trash2, ShieldAlert, Scale, Building, BookOpen } from 'lucide-react';
import PackageMarkingDiagram from './PackageMarkingDiagram';
import AddressBookModal from './AddressBookModal';
import { validateShippingQuantity, parseQtyValue, parseQtyUnit } from '../utils/regulatoryValidator';

export default function ShippingGuideWizard({ regMode, syncedItem, onAutoGenerateDocs }) {
  const [step, setStep] = useState(1);
  const [isOverpack, setIsOverpack] = useState(false);

  // Single package state
  const [unNumber, setUnNumber] = useState('UN1203');
  const [psn, setPsn] = useState('GASOLINE');
  const [techName, setTechName] = useState('');
  const [hazardClass, setHazardClass] = useState('3');
  const [subRisk, setSubRisk] = useState('');
  const [pkgGroup, setPkgGroup] = useState('II');
  const [pkgType, setPkgType] = useState('4G Fibreboard Box (UN Spec)');
  const [netQty, setNetQty] = useState('5.0 L');

  // Shipper & Consignee Address Book State (Persistent SQLite)
  const [shipperName, setShipperName] = useState('ACME Global Logistics');
  const [shipperAddress, setShipperAddress] = useState('100 Industrial Pkwy, Suite 400, Houston, TX 77001 USA');
  const [consigneeName, setConsigneeName] = useState('Metro Power Systems');
  const [consigneeAddress, setConsigneeAddress] = useState('50 Freight Way, Unit 12, London Heathrow TW6 2GW, UK');
  const [emergencyPhone, setEmergencyPhone] = useState('1-800-424-9300 (CHEMTREC #12345)');
  const [signatoryName, setSignatoryName] = useState('Jane Doe (Certified DG Specialist)');
  const [isAddressBookOpen, setIsAddressBookOpen] = useState(false);
  const [addressBookTarget, setAddressBookTarget] = useState('shippers');
  const [savedContacts, setSavedContacts] = useState([]);

  // Overpack Manifest Items State
  const [overpackItems, setOverpackItems] = useState([
    {
      id: '1',
      un_number: 'UN1203',
      proper_shipping_name: 'GASOLINE',
      class_division: '3',
      subsidiary_risk: '',
      packing_group: 'II',
      quantity_and_unit: '5.0 L',
      number_and_type_of_packagings: '1 Fibreboard Box (4G)',
      max_limit: '60.0 L'
    },
    {
      id: '2',
      un_number: 'UN3480',
      proper_shipping_name: 'LITHIUM ION BATTERIES',
      class_division: '9',
      subsidiary_risk: '',
      packing_group: '',
      quantity_and_unit: '2.0 kg G',
      number_and_type_of_packagings: '1 Fibreboard Box (4G)',
      max_limit: '35.0 kg'
    }
  ]);

  // Form for adding new item to Overpack
  const [newItemUn, setNewItemUn] = useState('UN1814');
  const [newItemPsn, setNewItemPsn] = useState('POTASSIUM HYDROXIDE SOLUTION');
  const [newItemClass, setNewItemClass] = useState('8');
  const [newItemSubRisk, setNewItemSubRisk] = useState('');
  const [newItemPg, setNewItemPg] = useState('II');
  const [newItemQty, setNewItemQty] = useState('1.0 L');
  const [newItemPkg, setNewItemPkg] = useState('1 Fibreboard Box (4G)');

  // Update specific field on an overpack item
  const handleUpdateOverpackItem = (id, field, value) => {
    setOverpackItems(prev => prev.map(it => it.id === id ? { ...it, [field]: value } : it));
  };

  // UN Live Validation & Sync State
  const [unMatchStatus, setUnMatchStatus] = useState(null);

  // Live UN Lookup Effect for Single Package UN Number Input
  useEffect(() => {
    if (!unNumber) {
      setUnMatchStatus(null);
      return;
    }

    const cleanUn = unNumber.trim().toUpperCase().replace(/\s+/g, '');
    if (cleanUn.length < 2) return;

    const timer = setTimeout(async () => {
      try {
        const res = await fetch(`/api/hazmat/search?q=${encodeURIComponent(cleanUn)}`);
        const data = await res.json();
        
        const targetClean = cleanUn.startsWith('UN') ? cleanUn : `UN${cleanUn}`;
        const exact = data.find(it => it.un_number.toUpperCase().replace(/\s+/g, '') === targetClean);
        const bestMatch = exact || (data.length > 0 ? data[0] : null);

        if (bestMatch) {
          setPsn(bestMatch.proper_shipping_name);
          setHazardClass(bestMatch.class_division);
          if (bestMatch.subsidiary_risk !== undefined) setSubRisk(bestMatch.subsidiary_risk || '');
          if (bestMatch.packing_group !== undefined) setPkgGroup(bestMatch.packing_group || '');
          setUnMatchStatus({ isMatched: true, item: bestMatch });
        } else {
          setUnMatchStatus({ isMatched: false, query: unNumber });
        }
      } catch (err) {
        console.error('Failed to lookup UN number:', err);
      }
    }, 250);

    return () => clearTimeout(timer);
  }, [unNumber]);

  // Live UN Lookup Effect for Overpack New Item UN Number Input
  useEffect(() => {
    if (!newItemUn) return;
    const cleanUn = newItemUn.trim().toUpperCase().replace(/\s+/g, '');
    if (cleanUn.length < 2) return;

    const timer = setTimeout(async () => {
      try {
        const res = await fetch(`/api/hazmat/search?q=${encodeURIComponent(cleanUn)}`);
        const data = await res.json();
        if (data && data.length > 0) {
          setNewItemPsn(data[0].proper_shipping_name);
          setNewItemClass(data[0].class_division);
          if (data[0].subsidiary_risk !== undefined) setNewItemSubRisk(data[0].subsidiary_risk || '');
          if (data[0].packing_group !== undefined) setNewItemPg(data[0].packing_group || '');
        }
      } catch (err) {
        console.error('Overpack item UN lookup error:', err);
      }
    }, 250);

    return () => clearTimeout(timer);
  }, [newItemUn]);

  useEffect(() => {
    if (syncedItem) {
      if (syncedItem.un_number) setUnNumber(syncedItem.un_number);
      if (syncedItem.proper_shipping_name) setPsn(syncedItem.proper_shipping_name);
      if (syncedItem.class_division) setHazardClass(syncedItem.class_division);
      if (syncedItem.subsidiary_risk !== undefined) setSubRisk(syncedItem.subsidiary_risk || '');
      if (syncedItem.packing_group !== undefined) setPkgGroup(syncedItem.packing_group || '');
      
      if (syncedItem.battery_details) {
        setNetQty(`${syncedItem.battery_details.netWeightKg || 1.5} kg`);
        setPkgType(syncedItem.battery_details.section?.includes('Section II') ? 'Strong Outer Box (Section II Excepted)' : '4G Fibreboard Box (UN Spec)');
      } else if (syncedItem.dot_49cfr?.non_bulk_pkg) {
        setPkgType(`UN Spec Code ${syncedItem.dot_49cfr.non_bulk_pkg} (Fibreboard / Steel)`);
      }

      // Auto-offer to add synced item to Overpack list if in Overpack mode
      const exists = overpackItems.some(it => it.un_number === syncedItem.un_number);
      if (!exists && syncedItem.un_number) {
        const newItem = {
          id: Date.now().toString(),
          un_number: syncedItem.un_number,
          proper_shipping_name: syncedItem.proper_shipping_name,
          class_division: syncedItem.class_division || '9',
          subsidiary_risk: syncedItem.subsidiary_risk || '',
          packing_group: syncedItem.packing_group || '',
          quantity_and_unit: '2.0 L',
          number_and_type_of_packagings: '1 Fibreboard Box (4G)',
          max_limit: '60.0 L'
        };
        setOverpackItems(prev => [newItem, ...prev]);
      }

      setStep(1);
    }
  }, [syncedItem]);

  // Load Address Book contacts from SQLite on mount
  const fetchSavedContacts = async () => {
    try {
      const res = await fetch('/api/contacts');
      if (res.ok) {
        const data = await res.json();
        setSavedContacts(data);
        const defaultShipper = data.find(c => (c.type === 'SHIPPER' || c.type === 'BOTH') && c.is_default);
        if (defaultShipper) {
          setShipperName(defaultShipper.company_name);
          setShipperAddress(`${defaultShipper.street_address}, ${defaultShipper.city}, ${defaultShipper.state_province} ${defaultShipper.postal_code} ${defaultShipper.country}`);
          if (defaultShipper.emergency_phone) setEmergencyPhone(defaultShipper.emergency_phone);
          if (defaultShipper.contact_person) setSignatoryName(defaultShipper.contact_person);
        }
        const defaultConsignee = data.find(c => (c.type === 'CONSIGNEE' || c.type === 'BOTH') && c.is_default);
        if (defaultConsignee) {
          setConsigneeName(defaultConsignee.company_name);
          setConsigneeAddress(`${defaultConsignee.street_address}, ${defaultConsignee.city}, ${defaultConsignee.state_province} ${defaultConsignee.postal_code} ${defaultConsignee.country}`);
        }
      }
    } catch (err) {
      console.error('Failed to load address book contacts:', err);
    }
  };

  useEffect(() => {
    fetchSavedContacts();
  }, []);

  const handleSelectContactFromModal = (contact) => {
    if (contact.type === 'SHIPPER' || addressBookTarget === 'shippers') {
      setShipperName(contact.company_name);
      setShipperAddress(`${contact.street_address}, ${contact.city}, ${contact.state_province} ${contact.postal_code} ${contact.country}`);
      if (contact.emergency_phone) setEmergencyPhone(contact.emergency_phone);
      if (contact.contact_person) setSignatoryName(contact.contact_person);
    } else {
      setConsigneeName(contact.company_name);
      setConsigneeAddress(`${contact.street_address}, ${contact.city}, ${contact.state_province} ${contact.postal_code} ${contact.country}`);
    }
    setIsAddressBookOpen(false);
  };

  // Add Item to Overpack Manifest
  const handleAddOverpackItem = () => {
    if (!newItemUn || !newItemPsn) return;
    const item = {
      id: Date.now().toString(),
      un_number: newItemUn.toUpperCase(),
      proper_shipping_name: newItemPsn.toUpperCase(),
      class_division: newItemClass,
      subsidiary_risk: newItemSubRisk || '',
      packing_group: newItemPg,
      quantity_and_unit: newItemQty || '1.0 L',
      number_and_type_of_packagings: newItemPkg || '1 Fibreboard Box (4G)',
      max_limit: '60.0 L'
    };
    setOverpackItems([...overpackItems, item]);
  };

  const handleRemoveOverpackItem = (id) => {
    setOverpackItems(overpackItems.filter(it => it.id !== id));
  };

  // Overpack Segregation Matrix Evaluation Logic (DOT 49 CFR 177.848 / IATA 9.3.11)
  const evaluateOverpackSegregation = () => {
    const conflicts = [];
    const forbiddenPairs = [
      ['3', '5.1'], ['5.1', '3'],
      ['2.1', '5.1'], ['5.1', '2.1'],
      ['4.1', '5.1'], ['5.1', '4.1'],
      ['4.2', '5.1'], ['5.1', '4.2'],
      ['4.3', '5.1'], ['5.1', '4.3'],
      ['5.1', '5.2'], ['5.2', '5.1'],
      ['8', '5.1'], ['5.1', '8']
    ];

    for (let i = 0; i < overpackItems.length; i++) {
      for (let j = i + 1; j < overpackItems.length; j++) {
        const c1 = overpackItems[i].class_division;
        const c2 = overpackItems[j].class_division;
        
        const isForbidden = forbiddenPairs.some(p => p[0] === c1 && p[1] === c2);
        if (isForbidden) {
          conflicts.push({
            item1: `${overpackItems[i].un_number} (${overpackItems[i].proper_shipping_name}) - Class ${c1}`,
            item2: `${overpackItems[j].un_number} (${overpackItems[j].proper_shipping_name}) - Class ${c2}`,
            rule: `PROHIBITED IN SAME OVERPACK: Class ${c1} and Class ${c2} must NOT be placed together inside the same outer packaging under ${regMode === '49CFR' ? '49 CFR 177.848(e)' : 'IATA DGR Table 9.3.A'}.`
          });
        }
      }
    }

    return {
      isCompliant: conflicts.length === 0,
      conflicts
    };
  };

  const segregationResult = evaluateOverpackSegregation();

  // Q-Value Calculation for All-Packed-In-One / Overpack (IATA 5.0.2.11)
  // Q = Sum(n_i / M_i) <= 1.0
  const calculateQValue = () => {
    let qTotal = 0;
    overpackItems.forEach(it => {
      const qtyNum = parseFloat(it.quantity_and_unit) || 1.0;
      const maxNum = parseFloat(it.max_limit) || 30.0;
      qTotal += (qtyNum / maxNum);
    });
    return qTotal.toFixed(2);
  };

  const qValue = calculateQValue();

  // Consolidated Document Generator Handler
  const handleAutoDoc = () => {
    let shipmentPayload;
    if (isOverpack) {
      shipmentPayload = {
        shipper_name: shipperName,
        shipper_address: shipperAddress,
        consignee_name: consigneeName,
        consignee_address: consigneeAddress,
        airway_bill_number: '016-98765432',
        departure_airport: 'JFK - New York',
        destination_airport: 'LHR - London Heathrow',
        shipment_type: regMode === 'IATA' ? 'CARGO_AIRCRAFT_ONLY' : 'GROUND',
        transport_mode: regMode === 'IATA' ? 'AIR' : 'GROUND',
        emergency_phone: emergencyPhone,
        signatory_name: signatoryName || 'Certified Overpack Specialist',
        is_overpack: true,
        overpack_id: 'OVERPACK 1 (1 x Outer Box)',
        items: overpackItems.map(it => ({
          un_number: it.un_number,
          proper_shipping_name: it.proper_shipping_name,
          class_division: it.class_division,
          packing_group: it.packing_group,
          number_and_type_of_packagings: `${it.number_and_type_of_packagings} (OVERPACK USED)`,
          quantity_and_unit: it.quantity_and_unit,
          packing_instruction: regMode === 'IATA' ? 'PI 364 / PI 851' : '49 CFR 173.202',
          authorization: 'OVERPACK COMPLIANT'
        }))
      };
    } else {
      shipmentPayload = {
        shipper_name: shipperName,
        shipper_address: shipperAddress,
        consignee_name: consigneeName,
        consignee_address: consigneeAddress,
        airway_bill_number: '016-98765432',
        departure_airport: 'JFK - New York',
        destination_airport: 'LHR - London Heathrow',
        shipment_type: regMode === 'IATA' ? 'CARGO_AIRCRAFT_ONLY' : 'GROUND',
        transport_mode: regMode === 'IATA' ? 'AIR' : 'GROUND',
        emergency_phone: emergencyPhone,
        signatory_name: signatoryName || 'Certified Hazmat Specialist',
        is_overpack: false,
        items: [
          {
            un_number: unNumber,
            proper_shipping_name: psn + (techName ? ` (${techName})` : ''),
            class_division: hazardClass,
            subsidiary_risk: subRisk,
            packing_group: pkgGroup,
            number_and_type_of_packagings: pkgType,
            quantity_and_unit: netQty,
            packing_instruction: syncedItem?.battery_details?.packing_instruction || (regMode === 'IATA' ? 'PI 364' : '49 CFR 173.202'),
            authorization: regMode === 'IATA' ? 'Cargo Aircraft Only' : 'DOT 49 CFR Compliant'
          }
        ]
      };
    }

    if (onAutoGenerateDocs) {
      onAutoGenerateDocs(shipmentPayload);
    }
  };

  const isBattery = ['UN3480', 'UN3481', 'UN3090', 'UN3091', 'UN3551', 'UN3552'].includes(unNumber.replace(/\s+/g, '').toUpperCase());

  return (
    <div style={{ padding: '24px' }}>
      
      {/* Synced Item Banner */}
      {syncedItem && (
        <div className="glass-card" style={{
          marginBottom: '20px',
          background: 'linear-gradient(135deg, rgba(255,153,0,0.2), rgba(0,240,255,0.2))',
          borderColor: '#ff9900',
          display: 'flex', alignItems: 'center', justifyContent: 'space-between'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <Zap color="#ff9900" size={24} />
            <div>
              <span style={{ fontSize: '11px', textTransform: 'uppercase', fontWeight: '800', color: '#ff9900' }}>
                Synchronized Active Material
              </span>
              <h4 style={{ fontSize: '15px', fontWeight: '800', color: '#fff' }}>
                {syncedItem.un_number} - {syncedItem.proper_shipping_name}
              </h4>
            </div>
          </div>
          <span className="badge badge-amber">Class {syncedItem.class_division || '9'}</span>
        </div>
      )}

      {/* Mode Switcher: Single Package vs Combined Overpack */}
      <div className="glass-panel" style={{ padding: '16px 24px', marginBottom: '24px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <Layers color="#00f0ff" size={24} />
          <div>
            <h3 style={{ fontSize: '16px', fontWeight: '800', color: '#ffffff' }}>Shipment Configuration Mode</h3>
            <p style={{ fontSize: '12px', color: '#94a3b8' }}>Select single package or consolidated overpack combined shipment</p>
          </div>
        </div>

        <div style={{ display: 'flex', background: 'rgba(0,0,0,0.4)', borderRadius: '10px', padding: '4px', border: '1px solid rgba(255,255,255,0.1)' }}>
          <button
            onClick={() => setIsOverpack(false)}
            style={{
              padding: '8px 16px', borderRadius: '8px', border: 'none', cursor: 'pointer', fontWeight: '700', fontSize: '13px',
              background: !isOverpack ? 'linear-gradient(135deg, #00f0ff, #0077ff)' : 'transparent',
              color: !isOverpack ? '#000' : '#94a3b8'
            }}
          >
            📦 Single Package
          </button>
          <button
            onClick={() => setIsOverpack(true)}
            style={{
              padding: '8px 16px', borderRadius: '8px', border: 'none', cursor: 'pointer', fontWeight: '700', fontSize: '13px',
              background: isOverpack ? 'linear-gradient(135deg, #ff9900, #ff5500)' : 'transparent',
              color: isOverpack ? '#fff' : '#94a3b8'
            }}
          >
            📦📦 Combined Shipment (Overpack)
          </button>
        </div>
      </div>

      {/* Wizard Step Progress Tracker */}
      <div className="glass-panel" style={{ padding: '20px 30px', marginBottom: '24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '16px' }}>
          {[
            { num: 1, title: isOverpack ? '1. Overpack Item Manifest' : '1. Identification & UN Classification' },
            { num: 2, title: isOverpack ? '2. Segregation & Q-Value Limits' : '2. Packaging & Quantity Limits' },
            { num: 3, title: isOverpack ? '3. Overpack Marking Diagram' : '3. Package Marking Diagram' },
            { num: 4, title: '4. Compliance Summary & Documents' }
          ].map((s) => (
            <div
              key={s.num}
              onClick={() => setStep(s.num)}
              style={{
                display: 'flex', alignItems: 'center', gap: '10px', cursor: 'pointer',
                opacity: step === s.num ? 1 : 0.6
              }}
            >
              <div style={{
                width: '32px', height: '32px', borderRadius: '50%',
                background: step === s.num ? 'linear-gradient(135deg, #ff9900, #ff5500)' : 'rgba(255,255,255,0.1)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontWeight: '700', fontSize: '14px', color: '#fff',
                boxShadow: step === s.num ? '0 0 12px rgba(255,153,0,0.4)' : 'none'
              }}>
                {s.num}
              </div>
              <span style={{ fontWeight: step === s.num ? '700' : '500', color: step === s.num ? '#ffffff' : '#94a3b8', fontSize: '14px' }}>
                {s.title}
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* Step Content */}
      <div className="glass-panel" style={{ padding: '28px' }}>
        
        {step === 1 && !isOverpack && (
          <div>
            <h2 style={{ fontSize: '20px', fontWeight: '700', marginBottom: '16px', color: '#ffffff' }}>
              Step 1: Hazardous Material Classification
            </h2>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
              <div>
                <label style={{ fontSize: '13px', fontWeight: '600', color: '#94a3b8', display: 'block', marginBottom: '6px' }}>UN or ID Number</label>
                <input type="text" className="input-field" value={unNumber} onChange={(e) => setUnNumber(e.target.value)} />
              </div>
              <div>
                <label style={{ fontSize: '13px', fontWeight: '600', color: '#94a3b8', display: 'block', marginBottom: '6px' }}>Proper Shipping Name</label>
                <input type="text" className="input-field" value={psn} onChange={(e) => setPsn(e.target.value)} />
              </div>
              <div>
                <label style={{ fontSize: '13px', fontWeight: '600', color: '#94a3b8', display: 'block', marginBottom: '6px' }}>Technical Name (if Generic / N.O.S.)</label>
                <input type="text" className="input-field" value={techName} onChange={(e) => setTechName(e.target.value)} placeholder="e.g. contains Acetone and Xylene" />
              </div>
              <div>
                <label style={{ fontSize: '13px', fontWeight: '600', color: '#94a3b8', display: 'block', marginBottom: '6px' }}>Primary Hazard Class</label>
                <select className="input-field" value={hazardClass} onChange={(e) => setHazardClass(e.target.value)}>
                  <option value="1.1">Class 1.1 - Explosives</option>
                  <option value="2.1">Class 2.1 - Flammable Gas</option>
                  <option value="2.2">Class 2.2 - Non-Flammable, Non-Toxic Gas</option>
                  <option value="2.3">Class 2.3 - Toxic Gas</option>
                  <option value="3">Class 3 - Flammable Liquids</option>
                  <option value="4.1">Class 4.1 - Flammable Solids</option>
                  <option value="4.2">Class 4.2 - Spontaneously Combustible</option>
                  <option value="4.3">Class 4.3 - Dangerous When Wet</option>
                  <option value="5.1">Class 5.1 - Oxidizer</option>
                  <option value="5.2">Class 5.2 - Organic Peroxide</option>
                  <option value="6.1">Class 6.1 - Toxic Substances</option>
                  <option value="7">Class 7 - Radioactive Material</option>
                  <option value="8">Class 8 - Corrosives</option>
                  <option value="9">Class 9 - Miscellaneous / Lithium Batteries</option>
                </select>
              </div>
              <div>
                <label style={{ fontSize: '13px', fontWeight: '600', color: '#94a3b8', display: 'block', marginBottom: '6px' }}>Subsidiary Risk (if applicable)</label>
                <select className="input-field" value={subRisk} onChange={(e) => setSubRisk(e.target.value)}>
                  <option value="">None (No Subsidiary Risk)</option>
                  <option value="2.1">2.1 - Flammable Gas</option>
                  <option value="3">3 - Flammable Liquid</option>
                  <option value="4.1">4.1 - Flammable Solid</option>
                  <option value="4.2">4.2 - Spontaneously Combustible</option>
                  <option value="4.3">4.3 - Dangerous When Wet</option>
                  <option value="5.1">5.1 - Oxidizer</option>
                  <option value="6.1">6.1 - Toxic Substance</option>
                  <option value="8">8 - Corrosive</option>
                </select>
              </div>
              <div>
                <label style={{ fontSize: '13px', fontWeight: '600', color: '#94a3b8', display: 'block', marginBottom: '6px' }}>Packing Group (PG)</label>
                <select className="input-field" value={pkgGroup} onChange={(e) => setPkgGroup(e.target.value)}>
                  <option value="I">PG I - Great Danger (High Hazard)</option>
                  <option value="II">PG II - Medium Danger (Medium Hazard)</option>
                  <option value="III">PG III - Minor Danger (Low Hazard)</option>
                  <option value="">None / Not Assigned (e.g. Class 2, 7, or Batteries)</option>
                </select>
              </div>
            </div>

            {/* Quick Packaging & Net Quantity Input Section in Step 1 */}
            <div className="glass-card" style={{
              marginTop: '20px',
              background: 'rgba(15, 23, 42, 0.7)',
              borderColor: 'rgba(255, 153, 0, 0.4)',
              padding: '16px 20px'
            }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '12px', flexWrap: 'wrap', gap: '8px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <Box color="#ff9900" size={18} />
                  <h4 style={{ fontSize: '14px', fontWeight: '800', color: '#ffffff' }}>
                    Packaging & Quantity Quick Setup (Input)
                  </h4>
                </div>
                <span className="badge badge-amber" style={{ fontSize: '10px' }}>Configurable in Step 1, 2 & Package Guide</span>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                <div>
                  <label style={{ fontSize: '12px', fontWeight: '600', color: '#00f0ff', display: 'block', marginBottom: '4px' }}>
                    Packaging Being Used
                  </label>
                  <input
                    type="text"
                    className="input-field"
                    value={pkgType}
                    onChange={(e) => setPkgType(e.target.value)}
                    placeholder="e.g. 4G Fibreboard Box (UN Spec) or 1A1 Steel Drum"
                    style={{ fontSize: '13px' }}
                  />
                  <div style={{ display: 'flex', gap: '4px', marginTop: '6px', flexWrap: 'wrap' }}>
                    {['4G Fibreboard Box (UN Spec)', '1A1 Steel Drum', '3H1 Plastic Jerrican', 'Strong Outer Box'].map(preset => (
                      <button
                        key={preset}
                        type="button"
                        onClick={() => setPkgType(preset)}
                        style={{
                          padding: '3px 8px', fontSize: '10px', fontWeight: '600', borderRadius: '4px',
                          background: pkgType === preset ? 'rgba(0,240,255,0.25)' : 'rgba(255,255,255,0.06)',
                          color: pkgType === preset ? '#00f0ff' : '#cbd5e1',
                          border: pkgType === preset ? '1px solid #00f0ff' : '1px solid rgba(255,255,255,0.1)',
                          cursor: 'pointer'
                        }}
                      >
                        {preset.split(' ')[0]} {preset.split(' ')[1]}
                      </button>
                    ))}
                  </div>
                </div>
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '4px' }}>
                    <label style={{ fontSize: '12px', fontWeight: '600', color: '#10b981' }}>
                      Net Quantity per Package
                    </label>
                    {(() => {
                      const activeItem = unMatchStatus?.item || syncedItem;
                      const qv = validateShippingQuantity(netQty, activeItem, regMode);
                      return (
                        <span style={{
                          fontSize: '10px',
                          fontWeight: '800',
                          padding: '1px 6px',
                          borderRadius: '4px',
                          background: 'rgba(0,0,0,0.4)',
                          color: qv.badgeColor,
                          border: `1px solid ${qv.badgeColor}`
                        }}>
                          {qv.status === 'COMPLIANT' ? '✓ VALID' : qv.status === 'CAO_REQUIRED' ? '✈️ CAO ONLY' : '⛔ EXCEEDED'}
                        </span>
                      );
                    })()}
                  </div>
                  <input
                    type="text"
                    className="input-field"
                    value={netQty}
                    onChange={(e) => setNetQty(e.target.value)}
                    placeholder="e.g. 5.0 L or 10 kg"
                    style={{
                      fontSize: '13px',
                      borderColor: validateShippingQuantity(netQty, unMatchStatus?.item || syncedItem, regMode).badgeColor
                    }}
                  />
                  <div style={{ display: 'flex', gap: '4px', marginTop: '6px', flexWrap: 'wrap' }}>
                    {['1.0 L', '5.0 L', '20.0 L', '1.0 kg', '5.0 kg'].map(q => (
                      <button
                        key={q}
                        type="button"
                        onClick={() => setNetQty(q)}
                        style={{
                          padding: '3px 8px', fontSize: '10px', fontWeight: '600', borderRadius: '4px',
                          background: netQty === q ? 'rgba(16,185,129,0.25)' : 'rgba(255,255,255,0.06)',
                          color: netQty === q ? '#10b981' : '#cbd5e1',
                          border: netQty === q ? '1px solid #10b981' : '1px solid rgba(255,255,255,0.1)',
                          cursor: 'pointer'
                        }}
                      >
                        {q}
                      </button>
                    ))}
                  </div>
                  {/* Step 1 Live Regulatory Quantity Pill */}
                  {(() => {
                    const activeItem = unMatchStatus?.item || syncedItem;
                    const qv = validateShippingQuantity(netQty, activeItem, regMode);
                    return (
                      <div style={{
                        marginTop: '8px',
                        padding: '6px 8px',
                        borderRadius: '5px',
                        background: qv.status === 'COMPLIANT'
                          ? 'rgba(16,185,129,0.1)'
                          : qv.status === 'CAO_REQUIRED'
                          ? 'rgba(234,88,12,0.15)'
                          : 'rgba(239,68,68,0.15)',
                        border: `1px solid ${qv.badgeColor}`,
                        fontSize: '11px',
                        color: '#cbd5e1',
                        lineHeight: '1.3'
                      }}>
                        <div style={{ fontWeight: '700', color: qv.badgeColor, marginBottom: '2px' }}>
                          {qv.status === 'COMPLIANT' ? '✅ Regulatory Compliance Verified' : qv.status === 'CAO_REQUIRED' ? '✈️ Cargo Aircraft Only Required' : '⛔ Exceeds Legal Limit'}
                        </div>
                        <div>{qv.message}</div>
                      </div>
                    );
                  })()}
                </div>
              </div>
            </div>

            {/* Live UN Hazmat Table Match Validation Card */}
            {unMatchStatus && unMatchStatus.isMatched && (
              <div className="glass-card" style={{
                marginTop: '20px',
                background: 'rgba(16, 185, 129, 0.1)',
                borderColor: '#10b981',
                padding: '16px 20px',
                display: 'flex', alignItems: 'center', justifyContent: 'space-between'
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <CheckCircle2 color="#10b981" size={28} />
                  <div>
                    <span className="badge badge-emerald" style={{ marginBottom: '4px', display: 'inline-block' }}>
                      ✅ VERIFIED UN HAZMAT TABLE RECORD
                    </span>
                    <h4 style={{ fontSize: '15px', fontWeight: '800', color: '#ffffff', margin: '4px 0 2px 0' }}>
                      {unMatchStatus.item.un_number} - {unMatchStatus.item.proper_shipping_name}
                    </h4>
                    <p style={{ fontSize: '11px', color: '#cbd5e1' }}>
                      Class {unMatchStatus.item.class_division} | Packing Group: {unMatchStatus.item.packing_group || 'N/A'} | ERG Guide #{unMatchStatus.item.dot_49cfr?.erg_guide || '154'}
                    </p>
                  </div>
                </div>
                <div style={{ textAlign: 'right', fontSize: '11px', color: '#10b981', fontWeight: '700' }}>
                  3,815 Active UN Records Synced
                </div>
              </div>
            )}

            {unMatchStatus && !unMatchStatus.isMatched && unNumber.length >= 3 && (
              <div className="glass-card" style={{
                marginTop: '20px',
                background: 'rgba(239, 68, 68, 0.12)',
                borderColor: '#ef4444',
                padding: '14px 18px',
                display: 'flex', alignItems: 'center', gap: '12px'
              }}>
                <ShieldAlert color="#ef4444" size={24} />
                <div>
                  <h5 style={{ fontSize: '13px', fontWeight: '800', color: '#ef4444' }}>
                    UN NUMBER NOT FOUND IN DATABASE
                  </h5>
                  <p style={{ fontSize: '11px', color: '#fda4af' }}>
                    No exact match for '{unNumber}' in the 3,815 registered UN substances. You can manually enter PSN and Class details above.
                  </p>
                </div>
              </div>
            )}

            {/* Shipper & Consignee Setup Card (SQLite Address Book) */}
            <div className="glass-card" style={{ marginTop: '20px', padding: '18px 20px', background: 'rgba(15,23,42,0.7)', borderColor: 'rgba(0, 240, 255, 0.3)' }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '14px', flexWrap: 'wrap', gap: '8px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <Building size={18} color="#00f0ff" />
                  <div>
                    <h4 style={{ fontSize: '14px', fontWeight: '800', color: '#fff', margin: 0 }}>
                      Shipper & Consignee Address Setup (SQLite Database)
                    </h4>
                    <p style={{ fontSize: '11px', color: '#94a3b8', margin: '2px 0 0 0' }}>
                      Stored in <code>ezship_addressbook.db</code> — auto-populates 2D box markings & carrier documents.
                    </p>
                  </div>
                </div>
                <button
                  type="button"
                  onClick={() => { setAddressBookTarget('shippers'); setIsAddressBookOpen(true); }}
                  className="btn btn-secondary"
                  style={{ fontSize: '11px', padding: '5px 12px', display: 'flex', alignItems: 'center', gap: '5px' }}
                >
                  <BookOpen size={14} /> Open Address Book
                </button>
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '14px' }}>
                {/* Shipper Selection & Display */}
                <div style={{ background: 'rgba(0,0,0,0.35)', padding: '12px', borderRadius: '8px', border: '1px solid rgba(255,153,0,0.25)' }}>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '6px' }}>
                    <label style={{ fontSize: '12px', fontWeight: '700', color: '#ff9900' }}>
                      Shipper (Origin / Consignor)
                    </label>
                    <select
                      className="input-field"
                      style={{ padding: '3px 6px', fontSize: '11px', width: 'auto', background: '#0b1120', color: '#ff9900', fontWeight: '700' }}
                      value={shipperName}
                      onChange={(e) => {
                        const sel = savedContacts.find(c => c.company_name === e.target.value);
                        if (sel) {
                          setShipperName(sel.company_name);
                          setShipperAddress(`${sel.street_address}, ${sel.city}, ${sel.state_province} ${sel.postal_code} ${sel.country}`);
                          if (sel.emergency_phone) setEmergencyPhone(sel.emergency_phone);
                          if (sel.contact_person) setSignatoryName(sel.contact_person);
                        } else {
                          setShipperName(e.target.value);
                        }
                      }}
                    >
                      {savedContacts.filter(c => c.type === 'SHIPPER' || c.type === 'BOTH').map(c => (
                        <option key={c.id} value={c.company_name}>
                          {c.company_name} {c.is_default ? '★' : ''}
                        </option>
                      ))}
                    </select>
                  </div>
                  <input
                    type="text"
                    className="input-field"
                    value={shipperName}
                    onChange={(e) => setShipperName(e.target.value)}
                    placeholder="Shipper Company Name"
                    style={{ fontSize: '12px', fontWeight: '700', marginBottom: '6px' }}
                  />
                  <textarea
                    className="input-field"
                    rows={2}
                    value={shipperAddress}
                    onChange={(e) => setShipperAddress(e.target.value)}
                    placeholder="Street Address, City, State/Province, Country"
                    style={{ fontSize: '11px', resize: 'vertical' }}
                  />
                  <div style={{ fontSize: '10px', color: '#ef4444', marginTop: '4px', fontWeight: '700' }}>
                    📞 24-HR Emergency: {emergencyPhone}
                  </div>
                </div>

                {/* Consignee Selection & Display */}
                <div style={{ background: 'rgba(0,0,0,0.35)', padding: '12px', borderRadius: '8px', border: '1px solid rgba(0,240,255,0.25)' }}>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '6px' }}>
                    <label style={{ fontSize: '12px', fontWeight: '700', color: '#00f0ff' }}>
                      Consignee (Destination / Receiver)
                    </label>
                    <select
                      className="input-field"
                      style={{ padding: '3px 6px', fontSize: '11px', width: 'auto', background: '#0b1120', color: '#00f0ff', fontWeight: '700' }}
                      value={consigneeName}
                      onChange={(e) => {
                        const sel = savedContacts.find(c => c.company_name === e.target.value);
                        if (sel) {
                          setConsigneeName(sel.company_name);
                          setConsigneeAddress(`${sel.street_address}, ${sel.city}, ${sel.state_province} ${sel.postal_code} ${sel.country}`);
                        } else {
                          setConsigneeName(e.target.value);
                        }
                      }}
                    >
                      {savedContacts.filter(c => c.type === 'CONSIGNEE' || c.type === 'BOTH').map(c => (
                        <option key={c.id} value={c.company_name}>
                          {c.company_name} {c.is_default ? '★' : ''}
                        </option>
                      ))}
                    </select>
                  </div>
                  <input
                    type="text"
                    className="input-field"
                    value={consigneeName}
                    onChange={(e) => setConsigneeName(e.target.value)}
                    placeholder="Consignee Company Name"
                    style={{ fontSize: '12px', fontWeight: '700', marginBottom: '6px' }}
                  />
                  <textarea
                    className="input-field"
                    rows={2}
                    value={consigneeAddress}
                    onChange={(e) => setConsigneeAddress(e.target.value)}
                    placeholder="Street Address, City, State/Province, Country"
                    style={{ fontSize: '11px', resize: 'vertical' }}
                  />
                </div>
              </div>
            </div>

            <div style={{ marginTop: '24px', textAlign: 'right' }}>
              <button className="btn-primary" onClick={() => setStep(2)}>
                Next: Packaging & Limits <ArrowRight size={18} />
              </button>
            </div>
          </div>
        )}

        {/* Step 1 in OVERPACK Mode */}
        {step === 1 && isOverpack && (
          <div>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
              <div>
                <h2 style={{ fontSize: '20px', fontWeight: '700', color: '#ffffff' }}>
                  Step 1: Consolidated Overpack Manifest Items
                </h2>
                <p style={{ fontSize: '12px', color: '#94a3b8' }}>
                  Add multiple dangerous goods inner packages to be combined in a single Overpack (IATA DGR 7.1.7 / 49 CFR 173.25)
                </p>
              </div>
            </div>

            {/* Overpack Items Table */}
            <div style={{ overflowX: 'auto', marginBottom: '24px' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', borderRadius: '8px', overflow: 'hidden' }}>
                <thead>
                  <tr style={{ background: 'rgba(255,255,255,0.08)', textTransform: 'uppercase', fontSize: '11px', color: '#94a3b8' }}>
                    <th style={{ padding: '12px', textAlign: 'left' }}>UN Number</th>
                    <th style={{ padding: '12px', textAlign: 'left' }}>Proper Shipping Name</th>
                    <th style={{ padding: '12px', textAlign: 'center' }}>Class</th>
                    <th style={{ padding: '12px', textAlign: 'center' }}>PG</th>
                    <th style={{ padding: '12px', textAlign: 'left' }}>Packaging Used</th>
                    <th style={{ padding: '12px', textAlign: 'left' }}>Net Quantity</th>
                    <th style={{ padding: '12px', textAlign: 'center' }}>Action</th>
                  </tr>
                </thead>
                <tbody>
                  {overpackItems.map((item) => (
                    <tr key={item.id} style={{ borderBottom: '1px solid rgba(255,255,255,0.05)', fontSize: '13px' }}>
                      <td style={{ padding: '10px 12px', fontWeight: '800', color: '#ff9900' }}>{item.un_number}</td>
                      <td style={{ padding: '10px 12px', color: '#fff' }}>{item.proper_shipping_name}</td>
                      <td style={{ padding: '10px 12px', textAlign: 'center' }}>
                        <span className="badge badge-cyan">Class {item.class_division}</span>
                      </td>
                      <td style={{ padding: '10px 12px', textAlign: 'center', color: '#cbd5e1' }}>{item.packing_group || '-'}</td>
                      <td style={{ padding: '10px 12px' }}>
                        <input
                          type="text"
                          className="input-field"
                          value={item.number_and_type_of_packagings}
                          onChange={(e) => handleUpdateOverpackItem(item.id, 'number_and_type_of_packagings', e.target.value)}
                          placeholder="e.g. 1 Fibreboard Box (4G)"
                          style={{ padding: '6px 10px', fontSize: '12px', minWidth: '160px' }}
                        />
                      </td>
                      <td style={{ padding: '10px 12px' }}>
                        {(() => {
                          const itemQv = validateShippingQuantity(item.quantity_and_unit, item, regMode);
                          return (
                            <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                              <input
                                type="text"
                                className="input-field"
                                value={item.quantity_and_unit}
                                onChange={(e) => handleUpdateOverpackItem(item.id, 'quantity_and_unit', e.target.value)}
                                placeholder="e.g. 2.0 L"
                                style={{
                                  padding: '6px 10px',
                                  fontSize: '12px',
                                  width: '90px',
                                  color: itemQv.badgeColor,
                                  borderColor: itemQv.badgeColor,
                                  fontWeight: '700'
                                }}
                              />
                              <span
                                title={itemQv.message}
                                style={{
                                  fontSize: '10px',
                                  padding: '2px 6px',
                                  borderRadius: '4px',
                                  background: 'rgba(0,0,0,0.5)',
                                  color: itemQv.badgeColor,
                                  border: `1px solid ${itemQv.badgeColor}`,
                                  fontWeight: '800',
                                  whiteSpace: 'nowrap',
                                  cursor: 'help'
                                }}
                              >
                                {itemQv.status === 'COMPLIANT' ? '✓ OK' : itemQv.status === 'CAO_REQUIRED' ? '✈️ CAO' : '⛔ LIMIT'}
                              </span>
                            </div>
                          );
                        })()}
                      </td>
                      <td style={{ padding: '10px 12px', textAlign: 'center' }}>
                        <button
                          onClick={() => handleRemoveOverpackItem(item.id)}
                          style={{ background: 'rgba(239,68,68,0.2)', border: '1px solid #ef4444', color: '#ef4444', padding: '6px 10px', borderRadius: '4px', cursor: 'pointer', fontSize: '12px' }}
                        >
                          <Trash2 size={14} /> Remove
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Quick Add Form to Overpack */}
            <div className="glass-card" style={{ background: 'rgba(255,255,255,0.02)', borderColor: 'rgba(255,153,0,0.3)', marginBottom: '20px' }}>
              <h4 style={{ fontSize: '14px', fontWeight: '700', color: '#ff9900', marginBottom: '12px' }}>
                ➕ Add Item to Overpack (Input Quantity & Packaging)
              </h4>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1.6fr 0.9fr 0.9fr 1.4fr 1.1fr auto', gap: '10px', alignItems: 'end' }}>
                <div>
                  <label style={{ fontSize: '11px', color: '#94a3b8' }}>UN Number</label>
                  <input type="text" className="input-field" value={newItemUn} onChange={e => setNewItemUn(e.target.value)} />
                </div>
                <div>
                  <label style={{ fontSize: '11px', color: '#94a3b8' }}>Proper Shipping Name</label>
                  <input type="text" className="input-field" value={newItemPsn} onChange={e => setNewItemPsn(e.target.value)} />
                </div>
                <div>
                  <label style={{ fontSize: '11px', color: '#94a3b8' }}>Class</label>
                  <select className="input-field" value={newItemClass} onChange={e => setNewItemClass(e.target.value)}>
                    <option value="3">3 - Flammable</option>
                    <option value="8">8 - Corrosive</option>
                    <option value="9">9 - Misc/Battery</option>
                    <option value="2.1">2.1 - Flam Gas</option>
                    <option value="5.1">5.1 - Oxidizer</option>
                    <option value="6.1">6.1 - Toxic</option>
                  </select>
                </div>
                <div>
                  <label style={{ fontSize: '11px', color: '#94a3b8' }}>PG</label>
                  <select className="input-field" value={newItemPg} onChange={e => setNewItemPg(e.target.value)}>
                    <option value="I">PG I</option>
                    <option value="II">PG II</option>
                    <option value="III">PG III</option>
                    <option value="">None</option>
                  </select>
                </div>
                <div>
                  <label style={{ fontSize: '11px', color: '#00f0ff', fontWeight: '600' }}>Packaging Used</label>
                  <input
                    type="text"
                    className="input-field"
                    value={newItemPkg}
                    onChange={e => setNewItemPkg(e.target.value)}
                    placeholder="e.g. 1 Fibreboard Box (4G)"
                  />
                </div>
                <div>
                  <label style={{ fontSize: '11px', color: '#10b981', fontWeight: '600' }}>Net Quantity</label>
                  <input
                    type="text"
                    className="input-field"
                    value={newItemQty}
                    onChange={e => setNewItemQty(e.target.value)}
                    placeholder="e.g. 1.0 L"
                  />
                </div>
                <button className="btn-primary" onClick={handleAddOverpackItem} style={{ padding: '10px 16px', whiteSpace: 'nowrap' }}>
                  <Plus size={16} /> Add Item
                </button>
              </div>
            </div>

            <div style={{ marginTop: '24px', textAlign: 'right' }}>
              <button className="btn-primary" onClick={() => setStep(2)}>
                Next: Segregation & Quantity Limits <ArrowRight size={18} />
              </button>
            </div>
          </div>
        )}

        {/* Step 2 Single Package */}
        {step === 2 && !isOverpack && (
          <div>
            <h2 style={{ fontSize: '20px', fontWeight: '700', marginBottom: '8px', color: '#ffffff' }}>
              Step 2: UN Specification Packaging & Net Quantity Validation
            </h2>
            <p style={{ fontSize: '12px', color: '#94a3b8', marginBottom: '20px' }}>
              Enter net quantity per package and validate against maximum allowed limits under {regMode === '49CFR' ? 'US DOT 49 CFR § 172.101' : 'IATA DGR Table 4.2 (66th Edition)'}.
            </p>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', marginBottom: '24px' }}>
              <div>
                <label style={{ fontSize: '13px', fontWeight: '700', color: '#00f0ff', display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '6px' }}>
                  <Box size={16} /> Packaging Being Used (Input or Select)
                </label>
                <div style={{ marginBottom: '8px' }}>
                  <input
                    type="text"
                    className="input-field"
                    value={pkgType}
                    onChange={(e) => setPkgType(e.target.value)}
                    placeholder="Enter or select packaging being used..."
                    style={{ fontSize: '14px', fontWeight: '600' }}
                  />
                </div>
                <div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap' }}>
                  {[
                    { label: '📦 4G Fibreboard Box', val: '4G Fibreboard Outer Box (UN Spec)' },
                    { label: '🛢️ 1A1 Steel Drum', val: '1A1 Steel Non-Removable Head Drum' },
                    { label: '🛢️ 1A2 Removable Drum', val: '1A2 Steel Removable Head Drum' },
                    { label: '🧴 3H1 Plastic Jerrican', val: '3H1 Plastic Jerrican' },
                    { label: '🧪 1H1 Plastic Drum', val: '1H1 Plastic Non-Removable Head Drum' },
                    { label: '🛡️ 4GV Combination Box', val: '4GV Special Combination Packaging' },
                    { label: '📦 Strong Outer Box', val: 'Strong Outer Box (Section II Excepted)' }
                  ].map(p => (
                    <button
                      key={p.label}
                      type="button"
                      onClick={() => setPkgType(p.val)}
                      style={{
                        padding: '4px 8px',
                        fontSize: '11px',
                        fontWeight: '700',
                        borderRadius: '5px',
                        cursor: 'pointer',
                        background: pkgType === p.val ? 'rgba(0,240,255,0.25)' : 'rgba(255,255,255,0.06)',
                        color: pkgType === p.val ? '#00f0ff' : '#cbd5e1',
                        border: pkgType === p.val ? '1px solid #00f0ff' : '1px solid rgba(255,255,255,0.1)',
                        transition: 'all 0.15s ease'
                      }}
                    >
                      {p.label}
                    </button>
                  ))}
                </div>
              </div>
              <div>
                <label style={{ fontSize: '13px', fontWeight: '700', color: '#10b981', display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '6px' }}>
                  <Scale size={16} /> Net Quantity per Package (User Input)
                </label>
                <div style={{ marginBottom: '8px' }}>
                  <input
                    type="text"
                    className="input-field"
                    value={netQty}
                    onChange={(e) => setNetQty(e.target.value)}
                    placeholder="e.g. 5.0 L or 10 kg"
                    style={{
                      fontSize: '14px',
                      fontWeight: '700',
                      borderColor: (() => {
                        const activeItem = unMatchStatus?.item || syncedItem;
                        const qv = validateShippingQuantity(netQty, activeItem, regMode);
                        return qv.badgeColor;
                      })()
                    }}
                  />
                </div>
                <div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap' }}>
                  {['0.5 L', '1.0 L', '2.5 L', '5.0 L', '20.0 L', '1.0 kg', '5.0 kg', '15.0 kg', '30.0 kg'].map(q => (
                    <button
                      key={q}
                      type="button"
                      onClick={() => setNetQty(q)}
                      style={{
                        padding: '4px 8px',
                        fontSize: '11px',
                        fontWeight: '700',
                        borderRadius: '5px',
                        cursor: 'pointer',
                        background: netQty === q ? 'rgba(16,185,129,0.25)' : 'rgba(255,255,255,0.06)',
                        color: netQty === q ? '#10b981' : '#cbd5e1',
                        border: netQty === q ? '1px solid #10b981' : '1px solid rgba(255,255,255,0.1)',
                        transition: 'all 0.15s ease'
                      }}
                    >
                      {q}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {/* Single Package Live Quantity Validation Card */}
            {(() => {
              const activeItem = unMatchStatus?.item || syncedItem;
              const qv = validateShippingQuantity(netQty, activeItem, regMode);

              return (
                <div className="glass-card" style={{
                  marginBottom: '24px',
                  background: qv.status === 'COMPLIANT'
                    ? 'rgba(16, 185, 129, 0.1)'
                    : qv.status === 'CAO_REQUIRED'
                    ? 'rgba(234, 88, 12, 0.15)'
                    : 'rgba(239, 68, 68, 0.15)',
                  borderColor: qv.badgeColor,
                  padding: '20px'
                }}>
                  <div style={{ display: 'flex', alignItems: 'flex-start', gap: '14px' }}>
                    {qv.status === 'COMPLIANT' ? (
                      <CheckCircle2 color="#10b981" size={32} />
                    ) : qv.status === 'CAO_REQUIRED' ? (
                      <AlertOctagon color="#ea580c" size={32} />
                    ) : (
                      <ShieldAlert color="#ef4444" size={32} />
                    )}
                    <div style={{ flex: 1 }}>
                      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '8px' }}>
                        <h3 style={{ fontSize: '16px', fontWeight: '800', color: qv.badgeColor }}>
                          {qv.status === 'COMPLIANT'
                            ? '✅ NET QUANTITY FULLY COMPLIANT'
                            : qv.status === 'CAO_REQUIRED'
                            ? '✈️ CARGO AIRCRAFT ONLY (CAO) MANDATORY'
                            : qv.status === 'FORBIDDEN'
                            ? '⛔ FORBIDDEN TRANSPORT: Prohibited for Air Transport'
                            : '⛔ MAXIMUM ALLOWED PACKAGE QUANTITY EXCEEDED!'}
                        </h3>
                        <span className="badge" style={{
                          background: 'rgba(0,0,0,0.5)',
                          color: qv.badgeColor,
                          border: `1px solid ${qv.badgeColor}`,
                          fontSize: '11px',
                          fontWeight: '800'
                        }}>
                          {qv.regulatoryCitation}
                        </span>
                      </div>
                      <p style={{ fontSize: '13px', color: '#cbd5e1', marginTop: '6px', lineHeight: '1.4' }}>
                        {qv.message}
                      </p>
                      
                      {/* Regulatory Sub-alerts */}
                      <div style={{ display: 'flex', gap: '10px', marginTop: '10px', flexWrap: 'wrap' }}>
                        {qv.isCaoRequired && (
                          <div style={{ display: 'flex', alignItems: 'center', gap: '6px', background: 'rgba(234,88,12,0.18)', border: '1px solid #ea580c', padding: '4px 8px', borderRadius: '4px', fontSize: '11px', color: '#fed7aa', fontWeight: '600' }}>
                            <span>✈️</span>
                            <span>CAO handling label must be affixed on Step 7 of the Package Guide.</span>
                          </div>
                        )}
                        {qv.requiresAbsorbent && (
                          <div style={{ display: 'flex', alignItems: 'center', gap: '6px', background: 'rgba(56,189,248,0.15)', border: '1px solid #38bdf8', padding: '4px 8px', borderRadius: '4px', fontSize: '11px', color: '#bae6fd', fontWeight: '600' }}>
                            <span>💧</span>
                            <span>Liquid DG: Absorbent cushioning required to absorb 100% of liquid (49 CFR 173.24a / IATA 5.0.2.12.1).</span>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
              );
            })()}

            {/* UN Specification Packaging Engineering & Certification Card */}
            <div className="glass-card" style={{ background: 'rgba(15, 23, 42, 0.8)', borderColor: 'rgba(0, 240, 255, 0.3)', padding: '20px', marginBottom: '24px' }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '14px', flexWrap: 'wrap', gap: '10px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                  <Box color="#00f0ff" size={24} />
                  <div>
                    <h3 style={{ fontSize: '15px', fontWeight: '800', color: '#ffffff' }}>
                      UN Specification Packaging Mark & Certification Summary
                    </h3>
                    <p style={{ fontSize: '11px', color: '#94a3b8' }}>
                      Certified under 49 CFR 178 / IATA Section 6 / ADR Chapter 6.1
                    </p>
                  </div>
                </div>
                <span className="badge badge-cyan" style={{ fontSize: '11px' }}>
                  Drop Test Level: {pkgGroup === 'I' ? 'X (1.8m)' : pkgGroup === 'III' ? 'Z (0.8m)' : 'Y (1.2m)'}
                </span>
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '12px' }}>
                <div style={{ background: 'rgba(0,0,0,0.4)', borderRadius: '8px', padding: '12px', border: '1px solid rgba(255,255,255,0.08)' }}>
                  <div style={{ fontSize: '10px', color: '#94a3b8', textTransform: 'uppercase' }}>Packaging Specification Code</div>
                  <div style={{ fontSize: '14px', fontWeight: '900', color: '#ff9900', marginTop: '4px', fontFamily: 'monospace' }}>
                    {pkgType.includes('4G') ? 'UN 4G / Y1.5 / S / 26 / USA / +AA1234'
                     : pkgType.includes('1A1') ? 'UN 1A1 / Y1.8 / 300 / 26 / USA / +AA5678'
                     : pkgType.includes('3H1') ? 'UN 3H1 / Y1.4 / 150 / 26 / USA / +AA9012'
                     : 'NON-UN SPEC (Strong Outer Packaging)'}
                  </div>
                </div>

                <div style={{ background: 'rgba(0,0,0,0.4)', borderRadius: '8px', padding: '12px', border: '1px solid rgba(255,255,255,0.08)' }}>
                  <div style={{ fontSize: '10px', color: '#94a3b8', textTransform: 'uppercase' }}>Hazard Classification</div>
                  <div style={{ fontSize: '13px', fontWeight: '800', color: '#ffffff', marginTop: '4px' }}>
                    Class {hazardClass} {subRisk ? `(Sub-risk ${subRisk})` : ''} | PG {pkgGroup || 'N/A'}
                  </div>
                </div>

                <div style={{ background: 'rgba(0,0,0,0.4)', borderRadius: '8px', padding: '12px', border: '1px solid rgba(255,255,255,0.08)' }}>
                  <div style={{ fontSize: '10px', color: '#94a3b8', textTransform: 'uppercase' }}>Liquid Containment Rules</div>
                  <div style={{ fontSize: '12px', fontWeight: '600', color: '#10b981', marginTop: '4px' }}>
                    {netQty.toLowerCase().includes('l') || netQty.toLowerCase().includes('ml')
                      ? 'Absorbent material & secondary leakproof liner required'
                      : 'Siftproof inner packaging & secure cushioning required'}
                  </div>
                </div>
              </div>
            </div>

            <div style={{ marginTop: '24px', display: 'flex', justifyContent: 'space-between' }}>
              <button className="btn-secondary" onClick={() => setStep(1)}>Back</button>
              <button className="btn-primary" onClick={() => setStep(3)}>
                Next: Package Marking Diagram & Full Checklist <ArrowRight size={18} />
              </button>
            </div>
          </div>

        )}

        {/* Step 2 OVERPACK Mode: Segregation & Q-Value Limits */}
        {step === 2 && isOverpack && (
          <div>
            <h2 style={{ fontSize: '20px', fontWeight: '700', marginBottom: '8px', color: '#ffffff' }}>
              Step 2: Overpack Segregation Matrix & Quantity Limits
            </h2>
            <p style={{ fontSize: '12px', color: '#94a3b8', marginBottom: '20px' }}>
              Verifies co-loading compatibility under {regMode === '49CFR' ? 'US DOT 49 CFR 177.848' : 'IATA DGR Section 9.3.11'} and calculates All-Packed-In-One Q-Value limit (IATA 5.0.2.11).
            </p>

            {/* Segregation Status Result Card */}
            <div className="glass-card" style={{
              marginBottom: '24px',
              background: segregationResult.isCompliant ? 'rgba(16, 185, 129, 0.1)' : 'rgba(239, 68, 68, 0.15)',
              borderColor: segregationResult.isCompliant ? '#10b981' : '#ef4444',
              padding: '20px'
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '14px', marginBottom: '12px' }}>
                {segregationResult.isCompliant ? (
                  <CheckCircle2 color="#10b981" size={32} />
                ) : (
                  <ShieldAlert color="#ef4444" size={32} />
                )}
                <div>
                  <h3 style={{ fontSize: '17px', fontWeight: '800', color: segregationResult.isCompliant ? '#10b981' : '#ef4444' }}>
                    {segregationResult.isCompliant ? '✅ ALL OVERPACK ITEMS ARE SEGREGATION COMPATIBLE' : '⛔ CRITICAL OVERPACK SEGREGATION VIOLATION'}
                  </h3>
                  <p style={{ fontSize: '12px', color: '#cbd5e1' }}>
                    {segregationResult.isCompliant
                      ? 'All items in this overpack may be co-packaged safely in the same outer packaging.'
                      : 'Incompatible hazardous materials detected inside the same overpack! Prohibited by transport regulations.'}
                  </p>
                </div>
              </div>

              {!segregationResult.isCompliant && (
                <div style={{ marginTop: '12px', background: 'rgba(0,0,0,0.4)', borderRadius: '8px', padding: '12px' }}>
                  {segregationResult.conflicts.map((conf, idx) => (
                    <div key={idx} style={{ color: '#fca5a5', fontSize: '13px', marginBottom: '6px' }}>
                      🔴 <strong>{conf.item1}</strong> + <strong>{conf.item2}</strong><br />
                      <span style={{ fontSize: '11px', color: '#fda4af' }}>{conf.rule}</span>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Q-Value Quantity Limit Calculator Card */}
            <div className="glass-card" style={{ background: 'rgba(0,0,0,0.3)', borderColor: 'rgba(0,240,255,0.3)', padding: '20px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '12px' }}>
                <Scale color="#00f0ff" size={24} />
                <div>
                  <h4 style={{ fontSize: '15px', fontWeight: '800', color: '#ffffff' }}>Overpack Q-Value Quantity Limit Calculator</h4>
                  <p style={{ fontSize: '11px', color: '#94a3b8' }}>Formula: Q = ∑ (Net Qty / Max Allowed Qty) ≤ 1.0 (IATA DGR 5.0.2.11)</p>
                </div>
              </div>

              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: 'rgba(255,255,255,0.05)', padding: '16px', borderRadius: '8px' }}>
                <div>
                  <span style={{ fontSize: '12px', color: '#94a3b8' }}>Calculated Q-Value:</span>
                  <div style={{ fontSize: '24px', fontWeight: '900', color: parseFloat(qValue) <= 1.0 ? '#10b981' : '#ef4444' }}>
                    Q = {qValue}
                  </div>
                </div>
                <div>
                  <span className={`badge ${parseFloat(qValue) <= 1.0 ? 'badge-emerald' : 'badge-amber'}`} style={{ fontSize: '12px', padding: '6px 12px' }}>
                    {parseFloat(qValue) <= 1.0 ? 'PASSED (Q ≤ 1.0)' : 'EXCEEDED (Q > 1.0)'}
                  </span>
                </div>
              </div>
            </div>

            <div style={{ marginTop: '24px', display: 'flex', justifyContent: 'space-between' }}>
              <button className="btn-secondary" onClick={() => setStep(1)}>Back</button>
              <button className="btn-primary" onClick={() => setStep(3)}>
                Next: Overpack Marking Diagram <ArrowRight size={18} />
              </button>
            </div>
          </div>
        )}

        {/* Step 3 Package Marking Diagram (Single Package & Overpack Modes) */}
        {step === 3 && (
          <div>
            <PackageMarkingDiagram
              unNumber={unNumber}
              psn={psn}
              techName={techName}
              hazardClass={hazardClass}
              subRisk={subRisk}
              packingGroup={pkgGroup}
              netQty={netQty}
              onNetQtyChange={setNetQty}
              pkgType={pkgType}
              onPkgTypeChange={setPkgType}
              regMode={regMode}
              isOverpack={isOverpack}
              overpackItems={overpackItems}
              onUpdateOverpackItem={handleUpdateOverpackItem}
              shipperName={shipperName}
              shipperAddress={shipperAddress}
              consigneeName={consigneeName}
              consigneeAddress={consigneeAddress}
              emergencyPhone={emergencyPhone}
              trackingNumber="7948 2940 1849"
            />

            <div style={{ marginTop: '24px', display: 'flex', justifyContent: 'space-between' }}>
              <button className="btn-secondary" onClick={() => setStep(2)}>Back</button>
              <button className="btn-primary" onClick={() => setStep(4)}>
                Next: Compliance Summary & Documents <ArrowRight size={18} />
              </button>
            </div>
          </div>
        )}

        {/* Step 4 Compliance Summary */}
        {step === 4 && (
          <div>
            <div style={{ textAlign: 'center', padding: '20px' }}>
              <CheckCircle2 size={56} color="#10b981" style={{ marginBottom: '12px' }} />
              <h2 style={{ fontSize: '22px', fontWeight: '800', color: '#ffffff' }}>
                {isOverpack ? 'Consolidated Overpack Shipment Validated & Ready!' : 'Shipment Package Verification Complete & Ready!'}
              </h2>
              <p style={{ fontSize: '14px', color: '#cbd5e1', marginTop: '6px', maxWidth: '650px', margin: '6px auto 20px auto' }}>
                Your {isOverpack ? 'Overpack combined shipment configuration' : 'single package configuration'} has been fully validated against {regMode === '49CFR' ? 'US DOT 49 CFR (173.25 & 177.848)' : 'IATA DGR 66th Edition (Sections 5.0.2.11, 7.1.7, 9.3.11)'}.
              </p>

              {/* Summary Card */}
              <div className="glass-card" style={{ maxWidth: '600px', margin: '0 auto 24px auto', textAlign: 'left', fontSize: '13px' }}>
                {isOverpack ? (
                  <div>
                    <div style={{ marginBottom: '8px' }}><span style={{ color: '#94a3b8' }}>Shipment Type:</span> <strong style={{ color: '#ff9900' }}>Consolidated Overpack Shipment</strong></div>
                    <div style={{ marginBottom: '8px' }}><span style={{ color: '#94a3b8' }}>Total Items Enclosed:</span> <strong style={{ color: '#fff' }}>{overpackItems.length} Dangerous Goods Inner Packages</strong></div>
                    <div style={{ marginBottom: '8px' }}><span style={{ color: '#94a3b8' }}>Segregation Status:</span> <strong style={{ color: '#10b981' }}>COMPATIBLE (0 Conflicts)</strong></div>
                    <div style={{ marginBottom: '8px' }}><span style={{ color: '#94a3b8' }}>Calculated Q-Value:</span> <strong style={{ color: '#00f0ff' }}>Q = {qValue} (≤ 1.0 Passed)</strong></div>
                    <div><span style={{ color: '#94a3b8' }}>Mandatory Markings:</span> <strong style={{ color: '#ff9900' }}>"OVERPACK" (min 12mm), Hazard Diamonds, UN Numbers</strong></div>
                  </div>
                ) : (
                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
                    <div><span style={{ color: '#94a3b8' }}>UN Number:</span> <strong style={{ color: '#ff9900' }}>{unNumber}</strong></div>
                    <div><span style={{ color: '#94a3b8' }}>Shipping Name:</span> <strong style={{ color: '#fff' }}>{psn}</strong></div>
                    <div><span style={{ color: '#94a3b8' }}>Hazard Class:</span> <strong style={{ color: '#00f0ff' }}>Class {hazardClass}</strong></div>
                    <div><span style={{ color: '#94a3b8' }}>Packaging Type:</span> <strong style={{ color: '#fff' }}>{pkgType}</strong></div>
                    <div><span style={{ color: '#94a3b8' }}>Net Quantity:</span> <strong style={{ color: '#fff' }}>{netQty}</strong></div>
                    <div><span style={{ color: '#94a3b8' }}>Transport Mode:</span> <strong style={{ color: '#10b981' }}>{regMode === 'IATA' ? 'AIR (IATA DGR)' : 'GROUND (49 CFR)'}</strong></div>
                  </div>
                )}
              </div>

              {/* Action Buttons */}
              <div style={{ display: 'flex', gap: '12px', justifyContent: 'center' }}>
                <button
                  className="btn-primary"
                  onClick={handleAutoDoc}
                  style={{
                    padding: '14px 24px',
                    fontSize: '15px',
                    background: 'linear-gradient(135deg, #10b981, #059669)',
                    boxShadow: '0 4px 16px rgba(16, 185, 129, 0.4)'
                  }}
                >
                  <FileText size={20} /> 📄 Auto-Generate Shipper's Declaration & Shipping Paper
                </button>
                <button className="btn-secondary" onClick={() => setStep(1)}>
                  Reset Wizard
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Address Book Modal */}
        <AddressBookModal
          isOpen={isAddressBookOpen}
          onClose={() => {
            setIsAddressBookOpen(false);
            fetchSavedContacts();
          }}
          defaultTab={addressBookTarget}
          onSelectContact={handleSelectContactFromModal}
        />

      </div>
    </div>
  );
}

