import React, { useState } from 'react';
import Navbar from './components/Navbar';
import HazmatLookup from './components/HazmatLookup';
import LithiumBatteryWizard from './components/LithiumBatteryWizard';
import SegregationMatrix from './components/SegregationMatrix';
import ShippingGuideWizard from './components/ShippingGuideWizard';
import DocumentGenerator from './components/DocumentGenerator';

export default function App() {
  const [activeTab, setActiveTab] = useState('lookup');
  const [regMode, setRegMode] = useState('49CFR'); // '49CFR' or 'IATA'
  const [syncedItem, setSyncedItem] = useState(null);
  const [syncedShipment, setSyncedShipment] = useState(null);

  const handleSyncToGuide = (item) => {
    setSyncedItem(item);
    setActiveTab('guide');
  };

  const handleAutoGenerateDocs = (shipment) => {
    setSyncedShipment(shipment);
    setActiveTab('documents');
  };

  return (
    <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
      <Navbar
        activeTab={activeTab}
        setActiveTab={setActiveTab}
        regMode={regMode}
        setRegMode={setRegMode}
      />

      <main style={{ flex: 1 }}>
        {activeTab === 'lookup' && (
          <HazmatLookup
            regMode={regMode}
            onSyncToGuide={handleSyncToGuide}
          />
        )}
        {activeTab === 'battery' && (
          <LithiumBatteryWizard
            regMode={regMode}
            onSyncToGuide={handleSyncToGuide}
          />
        )}
        {activeTab === 'segregation' && <SegregationMatrix regMode={regMode} />}
        {activeTab === 'guide' && (
          <ShippingGuideWizard
            regMode={regMode}
            syncedItem={syncedItem}
            onAutoGenerateDocs={handleAutoGenerateDocs}
          />
        )}
        {activeTab === 'documents' && (
          <DocumentGenerator
            regMode={regMode}
            syncedShipment={syncedShipment}
          />
        )}
      </main>

      <footer style={{
        textAlign: 'center', padding: '16px', fontSize: '12px', color: '#94a3b8',
        borderTop: '1px solid rgba(255,255,255,0.05)', marginTop: 'auto'
      }}>
        EZShip Hazmat & Dangerous Goods Platform &copy; 2026 | <strong style={{ color: '#ff9900' }}>Made by Jubail</strong> | Compliant with US DOT 49 CFR 171-180 & IATA DGR 66th Edition (2025/2026)
      </footer>
    </div>
  );
}
